runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: 2048web/index.html
  upload: 2048web/index.html

- url: /ai/ai.py
  script: main_probe.app

- url: /ai
  script: main.app

- url: /index\.html
  static_files: 2048web/index.html
  upload: 2048web/index.html

- url: /game.htm
  static_files: 2048web/game.htm
  upload: 2048web/game.htm

- url: /(.*)
  static_files: 2048web/\1
  upload: 2048web/(.*)

libraries:
- name: numpy
  version: latest
